name: Cloud Run Deploy

on:
  push:
    branches:
    - master
    - main
  workflow_dispatch:

jobs:
  deploy:
    uses: intersystems-community/demo-deployment/.github/workflows/deployment.yml@master
    with:
      # IMPORTANT: Change this name
      name: online
    secrets:
      # Do not forget to add Secret in GitHub Repoository Settings with name SERVICE_ACCOUNT_KEY
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}